/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "TCPWM_2.h"
#include "Clock_PWM_MAIN_1.h"
#include "DIR_REG_1.h"
#include "INTERNAL_STEP_1.h"
#include "INTERNAL_STEP_OUT_1.h"
#include "INTERNAL_STEP_OUT_1_aliases.h"
#include "PWM_OUT_A_1.h"
#include "PWM_OUT_A_1_aliases.h"
#include "PWM_OUT_B_1.h"
#include "PWM_OUT_B_1_aliases.h"
#include "DIR_OUT_B_1.h"
#include "DIR_OUT_B_1_aliases.h"
#include "DIR_OUT_A_1.h"
#include "DIR_OUT_A_1_aliases.h"
#include "STEP_INPUT_1.h"
#include "STEP_INPUT_1_aliases.h"
#include "DIR_INPUT_1.h"
#include "DIR_INPUT_1_aliases.h"
#include "STEP_INPUT_SOURCE_1.h"
#include "STEP_INPUT_SOURCE_1_aliases.h"
#include "DIR_INPUT_SOURCE_1.h"
#include "DIR_INPUT_SOURCE_1_aliases.h"
#include "TCPWM_1.h"
#include "TCPWM_4.h"
#include "TCPWM_3.h"
#include "PWM_OUT_B_2.h"
#include "PWM_OUT_B_2_aliases.h"
#include "PWM_OUT_A_2.h"
#include "PWM_OUT_A_2_aliases.h"
#include "INTERNAL_STEP_OUT_2.h"
#include "INTERNAL_STEP_OUT_2_aliases.h"
#include "INTERNAL_STEP_2.h"
#include "Clock_PWM_MAIN_2.h"
#include "Bootloadable_1.h"
#include "DIR_REG_2.h"
#include "DIR_OUT_B_2.h"
#include "DIR_OUT_B_2_aliases.h"
#include "DIR_OUT_A_2.h"
#include "DIR_OUT_A_2_aliases.h"
#include "STEP_INPUT_2.h"
#include "STEP_INPUT_2_aliases.h"
#include "DIR_INPUT_2.h"
#include "DIR_INPUT_2_aliases.h"
#include "STEP_INPUT_SOURCE_2.h"
#include "STEP_INPUT_SOURCE_2_aliases.h"
#include "DIR_INPUT_SOURCE_2.h"
#include "DIR_INPUT_SOURCE_2_aliases.h"
#include "I2C.h"
#include "I2C_I2C.h"
#include "I2C_PINS.h"
#include "I2C_I2C_PVT.h"
#include "I2C_PVT.h"
#include "I2C_BOOT.h"
#include "STATUS_LED_2.h"
#include "STATUS_LED_2_aliases.h"
#include "STATUS_LED_1.h"
#include "STATUS_LED_1_aliases.h"
#include "Pin_Sw.h"
#include "Pin_Sw_aliases.h"
#include "isr_GPIO.h"
#include "I2C_Addr.h"
#include "I2C_Addr_aliases.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

